In [134]:
%pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\user\anaconda_new\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\user\anaconda_new\lib\site-packages (2.3.5)
Requirement already satisfied: openpyxl in c:\users\user\anaconda_new\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\user\anaconda_new\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\user\anaconda_new\lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda_new\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda_new\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda_new\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\user\anaconda_new\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\user\anaconda_new\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda_new\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda_new\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [135]:
# Step 1 : Import reqired libbraies

import pandas as pd 
import numpy as np

In [169]:
#Step 2 : Load dataset

df=pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [137]:
#Step 3: Explore the dataset
#view first 5 records

df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [138]:
#view dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [139]:
#Statistical Summary
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [140]:
#Dataset Shape 
df.shape

(524, 15)

In [141]:
#Step 4 : Check Misiing values
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [142]:
#Step 5: Check Duplicate Records
df.duplicated().sum()

np.int64(11)

In [143]:
# Remove Duplicate records 
df.drop_duplicates(inplace=True)

In [144]:
df.duplicated().sum()

np.int64(0)

In [145]:
#Step 6 : Replace Invalid Values
#Replace common invalid with Nan

df.replace(['N/A', 'NULL', ''], np.nan, inplace=True)

In [146]:
#Step 7: remove extra space

df = df.apply(lambda x: x.str.strip() if x.dtype =='object' else x)

In [147]:
#Step 8: Standardize text format
#convert text into proper case

df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()

In [148]:
#Step 9: Validate Email Addresses
#Keep only valid email records

df =df[df['Email'].str.contains('@',na=False)]

In [149]:
# Step 10: Convert Date Columns

df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    dayfirst=True,
    errors='coerce'
)

df['Delivery_Date'] = pd.to_datetime(
    df['Delivery_Date'],
    dayfirst=True,
    errors='coerce'
)

In [150]:
#Step 11: Convert Numeric Columns
cols=['Qty','Unit_Price','Discount']
for c in cols:
    df[c] = pd.to_numeric(df[c],errors='coerce')

In [151]:
#Step 12: Remove Invalid Quantity
#remove records having negative or zero quantity.

df=df[df['Qty']>0]

In [152]:
df=df.dropna(subset=['Qty','Unit_Price'])

In [153]:
# Step 10: Convert Date Columns

df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    format='%d-%m-%Y',
    errors='coerce'
)

df['Delivery_Date'] = pd.to_datetime(
    df['Delivery_Date'],
    format='%d-%m-%Y',
    errors='coerce'
)

In [173]:
df = df.dropna(subset=['Qty', 'Unit_Price'])

In [174]:
df['Discount'] = df['Discount'].fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [175]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
Email            0
Phone            0
City             0
State            0
Product          0
Category         0
Qty              0
Unit_Price       0
Discount         0
Payment_Mode     0
Order_Status     0
Delivery_Date    0
dtype: int64

In [154]:
#Step 13: Fill Missing Values

df['Discount']=df['Discount'].fillna(0)
df['Phone'] =df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [155]:
df.isnull().sum()

Order_ID          0
Order_Date       44
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price        0
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
dtype: int64

In [156]:
#Step 14: Feature Engineering
#Total Sales

df['Sales']=df['Qty']*df['Unit_Price']

In [157]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,ORD1607,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,1497.0
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-03-09,2997.0

In [158]:
#Net Amount
df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [159]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,ORD1607,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,1497.0,1497.0
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0,2998.0
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-03-09,2997.0,2997.0

In [160]:
#Profit(Example: 20%)
df['Profit']=df['Net_Amount']*0.20

In [161]:
#Order Month

df['Month']=df['Order_Date'].dt.month_name()

In [162]:
df["Year"]=df['Order_Date'].dt.year

In [163]:
#Weekday

df['Weekday']=df['Order_Date'].dt.day_name()

In [164]:
#Step 15: Final Data Validation

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 343 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       343 non-null    object
 1   Order_Date     299 non-null    datetime64[ns]
 2   Customer_Name  343 non-null    object
 3   Email          343 non-null    object
 4   Phone          343 non-null    object
 5   City           343 non-null    object
 6   State          343 non-null    object
 7   Product        343 non-null    object
 8   Category       343 non-null    object
 9   Qty            343 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       343 non-null    float64
 12  Payment_Mode   343 non-null    object
 13  Order_Status   343 non-null    object
 14  Delivery_Date  341 non-null    datetime64[ns]
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          299 non-null    object
 19  Year           299 non-null    float64
 20  Weekday        299 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 59.0+ KB

In [168]:
df.isnull().sum()

Order_ID          0
Order_Date       44
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price        0
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Sales             0
Net_Amount        0
Profit            0
Month            44
Year             44
Weekday          44
dtype: int64

In [166]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,299,343.000000,343.000000,343.0,341,343.000000,343.000000,343.000000,299.0
mean,2025-04-03 21:40:20.066889728,3.332362,3252.352770,0.0,2025-04-11 07:23:24.105571840,11103.664723,11103.664723,2220.732945,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.0,2025-01-05 00:00:00,499.000000,499.000000,99.800000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.0,2025-02-24 00:00:00,2599.000000,2599.000000,519.800000,2025.0
50%,2025-04-06 00:00:00,4.000000,1999.000000,0.0,2025-04-13 00:00:00,5997.000000,5997.000000,1199.400000,2025.0
75%,2025-05-18 00:00:00,5.000000,4999.000000,0.0,2025-05-26 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,0.0,2025-07-08 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.473063,3026.092014,0.0,NaN,12194.528486,12194.528486,2438.905697,0.0

In [172]:
print(df.shape)
print(df.isnull().sum())

(524, 15)
Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [177]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
Email            0
Phone            0
City             0
State            0
Product          0
Category         0
Qty              0
Unit_Price       0
Discount         0
Payment_Mode     0
Order_Status     0
Delivery_Date    0
dtype: int64

In [179]:
df['Order_ID'].isnull().sum()

np.int64(0)

In [184]:
df['Order_ID'].astype(str).str.strip().eq('').sum()

np.int64(6)

In [186]:
df[df['Order_ID'].astype(str).str.strip().eq('')]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
71,,26-01-2025,Vikas,vikas17@gmail.com,9814518863.0,Mumbai,Maharashtra,Chair,Furniture,4.0,4999.0,15,NetBanking,Cancelled,31-01-2025
144,,15-01-2025,Sneha,sneha17@gmail.com,9151754926.0,Lucknow,UP,Bottle,Home,5.0,4999.0,5,COD,Returned,21-01-2025
217,,26-01-2025,Rahul,rahul38@gmail.com,9240228562.0,Mumbai,Maharashtra,Mouse,Electronics,5.0,499.0,10,UPI,Pending,28-01-2025
290,,24-06-2025,Rahul,rahul60@gmail.com,9250231514.0,Pune,Maharashtra,Laptop,Electronics,2.0,1499.0,,COD,Pending,27-06-2025
363,,23-06-2025,Sneha,sneha38@gmail.com,9546087489.0,Pune,Maharashtra,Shoes,Fashion,5.0,9999.0,,Wallet,Returned,28-06-2025
436,,14-01-2025,Priya,priya40@gmail.com,9861729728.0,Delhi,Delhi,Bottle,Home,2.0,499.0,0,COD,Cancelled,19-01-2025

In [188]:
df['Order_ID'] = df['Order_ID'].astype(str).str.strip()

mask = df['Order_ID'] == ''

df.loc[mask, 'Order_ID'] = [
    f'ORD{1002 + i}' for i in df.index[mask]
]

In [189]:
df['Order_ID'].astype(str).str.strip().eq('').sum()

np.int64(0)

In [190]:
df.to_csv('Clean_Ecommerce_Final.csv', index=False)

In [191]:
#Step 16:Export Clean Data
df.to_csv('Clean_Ecommerce_Finall.csv',index=False)

In [200]:
from sqlalchemy import create_engine

engine = create_engine(
    'mysql+pymysql://root:NewPassword%40123@localhost/ecommerce'
)

with engine.connect() as connection:
    print("MySQL Connected Successfully!")

MySQL Connected Successfully!

In [201]:
df.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

414